### ISSUE TITLE
Modernize look

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/baloise.github.io#1]
We could / should think about modernizing the look by switching to Jekyll based[ GitHub page themes](https://pages.github.com/themes/) as e.g. [Tactile](https://pages-themes.github.io/tactile/).

**Comment by joachimprinzbach** [comment]
Or we could adopt our CI Design from www.baloise.ch

**Comment by culmat** [comment]
See https://brandportal.baloise.com/de/home/corporate-design/webstyleguide.html

**Comment by joachimprinzbach** [comment]
This one is outdated ;-) and will be changed soon to the new styleguide on baloise.ch

**Comment by MarkusTiede** [comment]
@joachimprinzbach : would you be interested proposing a new Baloise CI conform Jekyll based GitHub page theme? Maybe within the scope of a gold card?

**Comment by culmat** [comment]
see https://github.com/baloise/baloise-bootstrap

**Comment by MarkusTiede** [comment]
More important than the look could / should (imho) also be the feel:
- currently the site is not responsive (barely usable on mobile devices)
- does not allow easy adding of content (e.g. [blog posts](https://jekyllrb.com/docs/posts/))

**Comment by MarkusTiede** [comment]
Switch to Jekyll based template has been done.
